# Generated by Django 6.0 on 2026-01-15 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers, +, spaces, hyphens, or parentheses', regex='^[\\d\\s\\+\\-\\(\\)]+$')]),
        ),
    ]
